### PR TITLE
Getdatasets

### PR DESCRIPTION
**Pull request by federicomarini**
Thoughts to keep in mind:
- if multiple datasets are used together, it can make sense to have a functions that gets them *both*, and especially how they are needed later - say: you need a named list? We make that named list for you, here.
- vignette still needs some expansion, but not so much on the coding aspect - rather, some tiny descriptive items about the datasets can be really useful

Other additions from your side?

### CODE REVIEW

**Comment by olapuentesantana** [comment]
I completed the documentation left for the functions for retrieving the data.

**Comment by olapuentesantana** [comment]
I am not quite sure what you meant with this " if multiple datasets are used together"?

The user could just store two contents in different variables using each function, right?

**Comment by federicomarini** [comment]
> The user could just store two contents in different variables using each function, right?

Yes, it can - it is more like, if a parameter needs the combination of two objects, then we can save this step to the user.
But seems it is not the case. Let's just keep this in a corner of the back of the mind :D

**Comment by olapuentesantana** [comment]
I also included some more info in the vignette related to the datasets

**Comment by olapuentesantana** [comment]
If you give me the OK I will merge the pull request

**Comment by federicomarini** [comment]
I added a couple of comments, all minor - but yes, in principle it looks good to me!

**Comment by olapuentesantana** [comment]
My mistake I commented it for a check and I forgot to uncomment

**Pull request merged**
